### ISSUE TITLE
Breaking in Do Expression

### ISSUE THREAD

**Issue by clemmy** [tc39/proposal-do-expressions#16]
Hi, I'm wondering about the possibility to support early breaks in do expressions. The rationale is that a similar functionality is available in labelled blocks:

```js
label: {
  console.log('boop');
  break label;
  console.log('beep');
}
```

Maybe something like:

```js
do label: {
  console.log('boop');
  break label;
  console.log('beep');
}
```

**Comment by pitaj** [comment]
Why do just put the existing code inside the do block?
