### ISSUE TITLE
Write more detailed explainer and spec text for Stage 2

### ISSUE THREAD

**Issue by littledan** [tc39/proposal-do-expressions#49]
I like the syntax restrictions and semantics described in [the slide deck for the June 2020 meeting](https://docs.google.com/presentation/d/14UYf30NeOd5TFZ4QJFigwBLZVotOwuQq3E-BCMIhGgk/edit). For Stage 2, I think we should have:
- A README that describes not just what and why at a high level (which you have done very well here) but also the major shape of the proposal, decisions and brief rationale
- First draft spec text of the semantics (I'm curious about the details of the restrictions described in the slides, which would be clearer from the spec text)

**Comment by bakkot** [comment]
I believe these are now done, as of https://github.com/tc39/proposal-do-expressions/pull/54. Some of those decisions are likely to change, of course. you can find spec text [here](https://tc39.es/proposal-do-expressions/).

Note that, as this did not achieve stage 2, at least some of these decisions will change before I bring it back to committee.
