### ISSUE TITLE
Async identifier/keyword reference inside class static block

### ISSUE THREAD

**Issue by Kingwl** [tc39/proposal-do-expressions#66]
According to [proposal-class-static-block](https://tc39.es/proposal-class-static-block/#sec-identifiers-static-semantics-early-errors)

```ts
const async = 42

class C {
  static {
    const foo = await // illegal
    const bar = do {
        const b = await // legal or illegal ?
    }
  }
}
```

It's basically means does the do expression is a `function boundary`( https://github.com/tc39/proposal-class-static-block/issues/43) ? Even the concept `function boundary` is not well-defined.

**Comment by bakkot** [comment]
Assuming you mean `await` rather than `async`, illegal. `do` has the same restrictions on syntax as the surrounding context.
