### ISSUE TITLE
EndsInIterationOrBareIfOrDeclaration missing case: Block with statements

### ISSUE THREAD

**Issue by Jack-Works** [tc39/proposal-do-expressions#68]
Only Block with no statements inside is mentioned.

**Comment by bakkot** [comment]
This is covered by the [chain production rule](https://tc39.es/ecma262/multipage/notational-conventions.html#sec-algorithm-conventions-syntax-directed-operations):

> Unless explicitly specified otherwise, all chain productions have an implicit definition for every operation that might be applied to that production's left-hand side nonterminal. The implicit definition simply reapplies the same operation with the same parameters, if any, to the chain production's sole right-hand side nonterminal and then returns the result.

**Comment by Jack-Works** [comment]
I implement this as:

```js
if (isBlock(node)) return checkEndsInIterationOrBareIfOrDeclaration(node.statements, labelSet, isLast);
```

Is this correct?

**Comment by bakkot** [comment]
As long as you handle the case that the list of statements is empty, yes. That's what [I do](https://github.com/tc39/proposal-do-expressions/blob/3ef6d463b8163cbf222846b40d17178cca36e9e1/ends-in-iteration-or-declaration/impl.js#L82-L90).
