### ISSUE TITLE
Return in function parameter initializer

### ISSUE THREAD

**Issue by Jack-Works** [tc39/proposal-do-expressions#73]
Is this allowed?

```js
function x(y = do { return true }) {}
```

**Comment by bakkot** [comment]
See [the readme](https://github.com/tc39/proposal-do-expressions#exceptions):

> `return` is allowed even within function parameter lists, as in function `f(x = do { return null; }) {}`.

**Comment by Jack-Works** [comment]
Hmm, can we ban it? It seems like `break` or `continue` in the `for` loop heads. And it's also hard to implement as the method in #63

**Comment by pitaj** [comment]
The problem is that you'd need different rules just for when the do expression is used in default parameter position. Whereas the restrictions to break and continue apply to all do blocks.

**Comment by Jack-Works** [comment]
> The problem is that you'd need different rules just for when the do expression is used in default parameter position. Whereas the restrictions to break and continue apply to all do blocks.

Can you give an example? I didn't catch your meaning

**Comment by EdSaleh** [comment]
https://github.com/tc39/proposal-do-expressions/issues/74

**Comment by Jack-Works** [comment]
implemented
